package com.example.eqvol.eqvola.Classes;

/**
 * Created by eqvol on 23.10.2017.
 */
public enum  AsyncMethodNames
{
    USER_REGISTRATION, USER_BEFORE_REGISTRATION, USER_CHECK_BEFORE_REGISTRATION, USER_RESEND_BEFORE_REGISTRATION, USER_LOGIN, CHECK_TOKEN, GET_USER, GET_USER_AVATAR, GET_COUNTRIES,
    SET_USER, GET_GROUPS, CREATE_ACCOUNT, GET_ACCOUNTS, USER_LOGOUT, GET_CATEGORIES, CREATE_TICKET,
    SEND_MESSAGE, GET_TICKETS, GET_DATA_FROM_TICKETS, GET_DATA_FROM_MESSAGES, GET_TICKET_MESSAGES,
    GET_NEW_MESSAGE, WAIT_AVATAR_LOADING, GET_ATTACHMENT, SET_ATTACHMENT, SET_USER_AVATAR, CHECK_EMAIL,
    GET_ACCOUNT_ORDERS, UPDATE_ACCOUNT_ORDERS, GET_NOTIFICATION, CLEAR_NOTIFICATIONS, GET_PAYMENTS, GET_WITHDRAWAL,
    GET_ACCOUNT_HOLDER_NAME, REQUEST_TRANSFER, GET_TRANSFERS
}
